### ISSUE TITLE
New module to read json data from a URL

### ISSUE THREAD

**Issue by Alex-developer** [AllskyTeam/allsky-modules#179]
New module that will read a 'flat' formated json dataset from a url and make it available to the overlay editor

**Comment by EricClaeys** [comment]
When I click on the Github link in the email I don't see your post.  Where is it?EricFrom: Alexandre Garcia ***@***.***>Sent: Friday, November 7, 2025 11:39:43 AMTo: AllskyTeam/allsky-modules ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [AllskyTeam/allsky-modules] New module to read json data from a URL (Issue #179)PsY4 left a comment (AllskyTeam/allsky-modules#179)Hi, I can't get the variables on the Overlay Editor, can you help me spot what's wrong ?I added the "Import JSON" to the Module Managerimage.png (view on web)

Debug Information shows result : Data retrieved okimage.png (view on web)

This is my file content :
{ "HA_TEMP": "13.2°C", "HA_HUMIDITY": "75%", "HA_PRESURE": "1030.1hPa", "HA_CLOUDS": "40%" }Can't find variables in Variable Manager....If a add a custom text field, it displays ??? (I tried ${HA_TEMP} and ${HA_HA_TEMP}image.png (view on web)
It also gives System messages :ERROR: No 'Type' defined for '${HA_TEMP}'; check in the Variable Manager in the WebUI's Overlay Editor page.  Using '???' instead.   (13 occurrences, last on November 07, 6:37:12 pm CET) 
ERROR: No 'Type' defined for '${HA_HA_TEMP}'; check in the Variable Manager in the WebUI's Overlay Editor page.  Using '???' instead.   (13 occurrences, last on November 07, 6:37:12 pm CET)
What did I do wrong ?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.
